### ISSUE TITLE
Unable to build with raylib

### ISSUE THREAD

**Issue by Lucas-Marcel** [mmxgn/RXYO#1]
How do i build it with raylib without getting errors? The error happens whenever i call #define MINIAUDIO_IMPLEMENTATION here are the errors https://pastebin.com/ybJXpC4n

**Comment by mmxgn** [comment]
Hi,

I am not sure what you mean by 

> The error happens whenever i call #define MINIAUDIO_IMPLEMENTATION 

What are the exact steps you are taking to build it?

**Comment by Lucas-Marcel** [comment]
Hi. I managed to make it work. Not your project though. But i could make raylib work with miniaudio.  #define MINIAUDIO_IMPLEMENTATION shouldnt definitelly be called. Since its alread implemented into raylib.
